<a href="https://colab.research.google.com/github/IronZiiz/data-science-start/blob/main/extra_hw_Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data frames and Series
##  goal of this homework is a exercise focusing on two concepts: DataFrame and Series. The task is to create a DataFrame and Series, and perform an exploratory analysis

In [1]:
import pandas as pd

In [4]:
# make a Data frame
## a small dict

dados = {'Nome':['Thiago', 'Matheus', 'João'],
         'Idade':[20, 25, 50],
         'Salario':[700, 3000, 20000]}

In [5]:
df = pd.DataFrame(dados)
df

      Nome  Idade  Salario
0   Thiago     20      700
1  Matheus     25     3000
2     João     50    20000

In [6]:
df.info()  # Explore: timestamps, var type, null data and memory

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     3 non-null      object
 1   Idade    3 non-null      int64
 2   Salario  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes

In [8]:
df['Salario'].mean()

7900.0

In [9]:
df['Salario'].median()

3000.0

In [ ]:
# make a Series

In [11]:
idades = pd.Series([20, 25, 50])
idades

0    20
1    25
2    50
dtype: int64

In [ ]:
# a small difference between DataFrame and Series
# although a DataFrame is a collection of Series, when we explore a DataFrame, there is an additional line that contains the name of each Series

In [12]:
idades.index

RangeIndex(start=0, stop=3, step=1)

In [13]:
idades.sort_values() # sort in ascending order

0    20
1    25
2    50
dtype: int64

In [15]:
idades.sort_values(ascending = False) # sort in descending order

2    50
1    25
0    20
dtype: int64

In [16]:
# about df is a set of series
nomes = pd.Series(["Ana", "Bruno", "Carla", "Diego", "Elisa"], name="nome")
idades = pd.Series([25, 34, 18, 40, 29], name="idade")
cidades = pd.Series(["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Curitiba", "Porto Alegre"], name="cidade")

In [19]:
df = pd.DataFrame({"Nomes":nomes,
                   "Idades":idades,
                   "Cidades":cidades})
df

   Nomes  Idades         Cidades
0    Ana      25       São Paulo
1  Bruno      34  Rio de Janeiro
2  Carla      18  Belo Horizonte
3  Diego      40        Curitiba
4  Elisa      29    Porto Alegre